# 异常处理

## 异常概述与异常体系结构
Java程序在执行过程中所发生的异常事件可以分为两类：  
- Error：Java虚拟机无法解决的严重问题。如JVM系统内部错误、资源耗尽等严重现象。比如：StackOverflowError、OOM。一般不编写针对性的代码进行处理  

```java
public class ErrorTest {
    public static void main(String[] args) {
        // 1. 栈溢出：java.lang.StackOverflowError
        // main(args);

        // 2. 堆溢出：java.lang.OutOfMemeryError
        // Integer[] arr = new Integer[1024 * 2024 * 1024];
    }
}
```

- Exception：其他因编程错误或偶然的外在因素导致的一般性问题，可以使用针对性的代码进行处理。例如：空指针访问、试图读取不存在的文件、网络连接中断、数组角标越界  

异常体系结构  
java.lang.Throwable  
- java.lang.Error：一般不编写针对性的代码进行处理  
- java.lang.Exception：可以进行异常的处理  
    - 编译时异常（checked）
        - IOException
            - FileNotFoundException
    - 运行时异常（unchecked）
        - NullPointException
        - ArrayIndexOutOfBoundsException
        - ClassCastException
        - NumberFormatException
        - InputMismatchException
        - ArithmeticException

面试题：常见的异常都有哪些？举例说明

## 常见异常
```java
import java.io.File;
import java.io.FileInputStream;
import java.util.Date;
import java.util.Scanner;

public class ExceptionTest {
    //*******************以下是编译时异常*******************
    public void test7() {
        File file = new File("hello.txt");
        FileInputStream fis = new FileInputStream(file); // Unhandled exception type FileNotFoundException
        
        int data = fis.read(); // Unhandled exception type IOException
        while (data != -1) {
            System.out.println((char) data);
            data = fis.read(); // Unhandled exception type IOException
        }
        fis.close(); // Unhandled exception type IOException
    }
    
    //*******************以下是运行时异常*******************
    // NullPointException
    public void test1() {
        // int[] arr = null;
        // System.out.println(arr[3]);
        String str = null;
        System.out.println(str.charAt(0));
    }

    // IndexOutOfBoundsException
    public void test2() {
        // ArrayIndexOutOfBoundsException
        // int[] arr = new int[10];
        // System.out.println(arr[10]);
        // StringIndexOutOfBoundsException
        String str = "abc";
        System.out.println(str.charAt(3));
    }

    // ClassCastException 类型转换异常
    public void test3() {
        Object obj = new Date();
        String str = (String) obj;
    }

    // NumberFormatException
    public void test4() {
        String str = "abc";
        int num = Integer.parseInt(str);
    }
    
    // InputMismatchException
    public void test5() {
        Scanner scanner = new Scanner(System.in);
        int score = scanner.nextInt(); // 终端输入abc
        System.out.println(score);
        scanner.close();
    }

    // ArithmeticException 算术异常
    public void test6() {
        int a = 10;
        int b = 0;
        System.out.println(a/b);
    }   
    public static void main(String[] args) {
        ExceptionTest test = new ExceptionTest();
        test.test6();
    }
}
```

## 异常处理机制一：try-catch-finally
一、异常的处理：抓抛模型  
过程一：“抛”，程序在正常执行的过程中，一旦出现异常，就会在异常代码处生成一个对应异常类的对象，并将此对象抛出。一旦抛出对象以后，其后的代码就不再执行  
过程二：“抓”，可以理解为异常处理的方式，分`try-catch-finally`和`throws`两种

二、`try-catch-finally`的使用
1. finally是可选的  
2. 使用try将可能出现异常代码包装起来，在执行过程中，一旦出现异常，就会生成一个对应异常类的对象，根据此对象的类型，去catch中进行匹配  
3. 一旦try中的异常对象匹配到某一个catch时，就进入catch中进行异常的处理。一旦处理完成后，就跳出当前的try-catch结构（在没有写finally的情况）。继续执行其后的代码  
4. catch中的异常类型如果没有子父类关系，则谁声明在上，谁声明在下无所谓  
    catch中的异常类型如果满足子父类关系，则要求子类一定声明在父类的上面，否则报错  
5. 常用的异常对象处理的方式
    - String getMessage()
    - printStackTrace()
6. 在try结构中声明的变量，在出了try结构以后，就不能再被调用  
7. finally中声明的是一定会被执行的代码。即使catch中又出现异常了，try中有return语句，catch中有return语句等情况
8. 像数据库连接、输入输出流、网络编程Socket等资源，JVM是不能自动回收的，我们需要手动的进行资源的释放。此时的资源释放，就需要声明在finally中

体会1：使用try-catch-finally处理编译时异常，使得程序在编译时不再报错，但是运行时仍可能报错。相当于我们使用try-catch-finally将一个编译时可能出现的异常，延迟到运行时出现  

体会2：开发中，由于运行时异常比较常见，所以我们通常就不针对运行时异常编写try-catch-finally了  
但针对编译时的异常，一定要考虑异常的处理

```java
try{
    // 可能出现异常的代码
}catch(异常类型1 变量名1){
    // 处理异常的方式1
}catch(异常类型2 变量名2){
    // 处理异常的方式2
}catch(异常类型3 变量名3){
    // 处理异常的方式3
}
....
finally{
    // 一定会执行的代码
}
```

```java
public void test1() {
    String str = "abc";
    try {
        System.out.println("1");
        int num = Integer.parseInt(str);
    } catch (NumberFormatException e) {
        System.out.println("出现数值转换异常");
        // String getMessage()
        // System.out.println(e.getMessage());
        // printStackTrace()
        // e.printStackTrace();
    }
    // System.out.println(num); // 报错：在try结构中声明的变量，在出了try结构以后，就不能再被调用
}
```

## 异常处理机制二：throws
throws + 异常类型
1. `throws + 异常类型`写在方法的声明处，指明此方法执行时，可能会抛出的异常类型。  
一旦当方法体执行时出现异常，仍会在异常代码出生成一个异常类的对象，此对象满足`throws`后异常类型时，就会被抛出。异常代码后续的代码不再执行  
2. `try-catch-fianlly`：真正的将异常给处理掉了  
`throws`的方式只是将异常抛给了方法的调用者，并没有真正将异常处理掉
3. 开发中如何选择使用`try-catch-fianlly`还是`throws`？  
    - 如果父类中被重写的方法没有`throws`方法处理异常，则子类重写的方法也不能使用`throws`，意味着如果子类重写的方法中有异常，必须使用`try-catch-fianlly`方法处理  
    - 执行的方法a中，先后又调用了另外的几个方法，这几个方法是递进关系执行的（后面的方法中会用到前面方法中的结果）。建议这几个方法使用`throws`的方法处理，而执行的方法a可以考虑使用`try-catch-finally`

```java
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;


public class ExceptionTest {
    public static void main(String[] args) {
        try {
            method2();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public static void method2() throws FileNotFoundException, IOException {
        method1();
    }

    public static void method1() throws FileNotFoundException, IOException {
        File file = new File("hello.txt");
        FileInputStream fis = new FileInputStream(file); // Unhandled exception type FileNotFoundException
        
        int data = fis.read(); // Unhandled exception type IOException
        while (data != -1) {
            System.out.println((char) data);
            data = fis.read(); // Unhandled exception type IOException
        }
        fis.close(); // Unhandled exception type IOException
    }
}
```

## 手动抛出异常：throw
关于异常对象的产生：  
- 系统自动生成的异常对象  
- 手动生成一个异常对象，并抛出throw
```java
public class StudentTest {
    public static void main(String[] args) {
        try {
            Student s = new Student();
            s.regist(-1001);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
}

class Student {
    private int id;

    public void regist(int id) throws Exception {
        if (id > 0) {
            this.id = id;
        } else {
            throw new Exception("您输入的数据非法！");
        }
    }
}
```

## 用户自定义异常类
如何自定义异常类？  
1. 继承于现有的异常结构：RuntimeException、Exception  
2. 提供全局常量：serialVersionUID  
3. 提供重载的构造器
```java
public class MyException extends RuntimeException{
    static final long serialVersionUID = -7034897190745766939L;

    public MyException() {

    }

    public MyException(String msg) {
        super(msg);
    }
}
```